export const countrycodes = [
  { "name": "Afghanistan", "isdcode": "+93", "code": "AF" },
  { "name": "Aland Islands", "isdcode": "+358", "code": "AX" },
  { "name": "Albania", "isdcode": "+355", "code": "AL" },
  { "name": "Algeria", "isdcode": "+213", "code": "DZ" },
  { "name": "AmericanSamoa", "isdcode": "+1684", "code": "AS" },
  { "name": "Andorra", "isdcode": "+376", "code": "AD" },
  { "name": "Angola", "isdcode": "+244", "code": "AO" },
  { "name": "Anguilla", "isdcode": "+1264", "code": "AI" },
  { "name": "Antarctica", "isdcode": "+672", "code": "AQ" },
  { "name": "Antigua and Barbuda", "isdcode": "+1268", "code": "AG" },
  { "name": "Argentina", "isdcode": "+54", "code": "AR" },
  { "name": "Armenia", "isdcode": "+374", "code": "AM" },
  { "name": "Aruba", "isdcode": "+297", "code": "AW" },
  { "name": "Australia", "isdcode": "+61", "code": "AU" },
  { "name": "Austria", "isdcode": "+43", "code": "AT" },
  { "name": "Azerbaijan", "isdcode": "+994", "code": "AZ" },
  { "name": "Bahamas", "isdcode": "+1242", "code": "BS" },
  { "name": "Bahrain", "isdcode": "+973", "code": "BH" },
  { "name": "Bangladesh", "isdcode": "+880", "code": "BD" },
  { "name": "Barbados", "isdcode": "+1246", "code": "BB" },
  { "name": "Belarus", "isdcode": "+375", "code": "BY" },
  { "name": "Belgium", "isdcode": "+32", "code": "BE" },
  { "name": "Belize", "isdcode": "+501", "code": "BZ" },
  { "name": "Benin", "isdcode": "+229", "code": "BJ" },
  { "name": "Bermuda", "isdcode": "+1441", "code": "BM" },
  { "name": "Bhutan", "isdcode": "+975", "code": "BT" },
  {
    "name": "Bolivia, Plurinational State of bolivia",
    "isdcode": "+591",
    "code": "BO"
  },
  { "name": "Bosnia and Herzegovina", "isdcode": "+387", "code": "BA" },
  { "name": "Botswana", "isdcode": "+267", "code": "BW" },
  { "name": "Brazil", "isdcode": "+55", "code": "BR" },
  {
    "name": "British Indian Ocean Territory",
    "isdcode": "+246",
    "code": "IO"
  },
  { "name": "Brunei Darussalam", "isdcode": "+673", "code": "BN" },
  { "name": "Bulgaria", "isdcode": "+359", "code": "BG" },
  { "name": "Burkina Faso", "isdcode": "+226", "code": "BF" },
  { "name": "Burundi", "isdcode": "+257", "code": "BI" },
  { "name": "Cambodia", "isdcode": "+855", "code": "KH" },
  { "name": "Cameroon", "isdcode": "+237", "code": "CM" },
  { "name": "Canada", "isdcode": "+1", "code": "CA" },
  { "name": "Cape Verde", "isdcode": "+238", "code": "CV" },
  { "name": "Cayman Islands", "isdcode": "+ 345", "code": "KY" },
  { "name": "Central African Republic", "isdcode": "+236", "code": "CF" },
  { "name": "Chad", "isdcode": "+235", "code": "TD" },
  { "name": "Chile", "isdcode": "+56", "code": "CL" },
  { "name": "China", "isdcode": "+86", "code": "CN" },
  { "name": "Christmas Island", "isdcode": "+61", "code": "CX" },
  { "name": "Cocos (Keeling) Islands", "isdcode": "+61", "code": "CC" },
  { "name": "Colombia", "isdcode": "+57", "code": "CO" },
  { "name": "Comoros", "isdcode": "+269", "code": "KM" },
  { "name": "Congo", "isdcode": "+242", "code": "CG" },
  {
    "name": "Congo, The Democratic Republic of the Congo",
    "isdcode": "+243",
    "code": "CD"
  },
  { "name": "Cook Islands", "isdcode": "+682", "code": "CK" },
  { "name": "Costa Rica", "isdcode": "+506", "code": "CR" },
  { "name": "Cote d'Ivoire", "isdcode": "+225", "code": "CI" },
  { "name": "Croatia", "isdcode": "+385", "code": "HR" },
  { "name": "Cuba", "isdcode": "+53", "code": "CU" },
  { "name": "Cyprus", "isdcode": "+357", "code": "CY" },
  { "name": "Czech Republic", "isdcode": "+420", "code": "CZ" },
  { "name": "Denmark", "isdcode": "+45", "code": "DK" },
  { "name": "Djibouti", "isdcode": "+253", "code": "DJ" },
  { "name": "Dominica", "isdcode": "+1767", "code": "DM" },
  { "name": "Dominican Republic", "isdcode": "+1849", "code": "DO" },
  { "name": "Ecuador", "isdcode": "+593", "code": "EC" },
  { "name": "Egypt", "isdcode": "+20", "code": "EG" },
  { "name": "El Salvador", "isdcode": "+503", "code": "SV" },
  { "name": "Equatorial Guinea", "isdcode": "+240", "code": "GQ" },
  { "name": "Eritrea", "isdcode": "+291", "code": "ER" },
  { "name": "Estonia", "isdcode": "+372", "code": "EE" },
  { "name": "Ethiopia", "isdcode": "+251", "code": "ET" },
  { "name": "Falkland Islands (Malvinas)", "isdcode": "+500", "code": "FK" },
  { "name": "Faroe Islands", "isdcode": "+298", "code": "FO" },
  { "name": "Fiji", "isdcode": "+679", "code": "FJ" },
  { "name": "Finland", "isdcode": "+358", "code": "FI" },
  { "name": "France", "isdcode": "+33", "code": "FR" },
  { "name": "French Guiana", "isdcode": "+594", "code": "GF" },
  { "name": "French Polynesia", "isdcode": "+689", "code": "PF" },
  { "name": "Gabon", "isdcode": "+241", "code": "GA" },
  { "name": "Gambia", "isdcode": "+220", "code": "GM" },
  { "name": "Georgia", "isdcode": "+995", "code": "GE" },
  { "name": "Germany", "isdcode": "+49", "code": "DE" },
  { "name": "Ghana", "isdcode": "+233", "code": "GH" },
  { "name": "Gibraltar", "isdcode": "+350", "code": "GI" },
  { "name": "Greece", "isdcode": "+30", "code": "GR" },
  { "name": "Greenland", "isdcode": "+299", "code": "GL" },
  { "name": "Grenada", "isdcode": "+1473", "code": "GD" },
  { "name": "Guadeloupe", "isdcode": "+590", "code": "GP" },
  { "name": "Guam", "isdcode": "+1671", "code": "GU" },
  { "name": "Guatemala", "isdcode": "+502", "code": "GT" },
  { "name": "Guernsey", "isdcode": "+44", "code": "GG" },
  { "name": "Guinea", "isdcode": "+224", "code": "GN" },
  { "name": "Guinea-Bissau", "isdcode": "+245", "code": "GW" },
  { "name": "Guyana", "isdcode": "+595", "code": "GY" },
  { "name": "Haiti", "isdcode": "+509", "code": "HT" },
  {
    "name": "Holy See (Vatican City State)",
    "isdcode": "+379",
    "code": "VA"
  },
  { "name": "Honduras", "isdcode": "+504", "code": "HN" },
  { "name": "Hong Kong", "isdcode": "+852", "code": "HK" },
  { "name": "Hungary", "isdcode": "+36", "code": "HU" },
  { "name": "Iceland", "isdcode": "+354", "code": "IS" },
  { "name": "India", "isdcode": "+91", "code": "IN" },
  { "name": "Indonesia", "isdcode": "+62", "code": "ID" },
  {
    "name": "Iran, Islamic Republic of Persian Gulf",
    "isdcode": "+98",
    "code": "IR"
  },
  { "name": "Iraq", "isdcode": "+964", "code": "IQ" },
  { "name": "Ireland", "isdcode": "+353", "code": "IE" },
  { "name": "Isle of Man", "isdcode": "+44", "code": "IM" },
  { "name": "Israel", "isdcode": "+972", "code": "IL" },
  { "name": "Italy", "isdcode": "+39", "code": "IT" },
  { "name": "Jamaica", "isdcode": "+1876", "code": "JM" },
  { "name": "Japan", "isdcode": "+81", "code": "JP" },
  { "name": "Jersey", "isdcode": "+44", "code": "JE" },
  { "name": "Jordan", "isdcode": "+962", "code": "JO" },
  { "name": "Kazakhstan", "isdcode": "+77", "code": "KZ" },
  { "name": "Kenya", "isdcode": "+254", "code": "KE" },
  { "name": "Kiribati", "isdcode": "+686", "code": "KI" },
  {
    "name": "Korea, Democratic People's Republic of Korea",
    "isdcode": "+850",
    "code": "KP"
  },
  {
    "name": "Korea, Republic of South Korea",
    "isdcode": "+82",
    "code": "KR"
  },
  { "name": "Kuwait", "isdcode": "+965", "code": "KW" },
  { "name": "Kyrgyzstan", "isdcode": "+996", "code": "KG" },
  { "name": "Laos", "isdcode": "+856", "code": "LA" },
  { "name": "Latvia", "isdcode": "+371", "code": "LV" },
  { "name": "Lebanon", "isdcode": "+961", "code": "LB" },
  { "name": "Lesotho", "isdcode": "+266", "code": "LS" },
  { "name": "Liberia", "isdcode": "+231", "code": "LR" },
  { "name": "Libyan Arab Jamahiriya", "isdcode": "+218", "code": "LY" },
  { "name": "Liechtenstein", "isdcode": "+423", "code": "LI" },
  { "name": "Lithuania", "isdcode": "+370", "code": "LT" },
  { "name": "Luxembourg", "isdcode": "+352", "code": "LU" },
  { "name": "Macao", "isdcode": "+853", "code": "MO" },
  { "name": "Macedonia", "isdcode": "+389", "code": "MK" },
  { "name": "Madagascar", "isdcode": "+261", "code": "MG" },
  { "name": "Malawi", "isdcode": "+265", "code": "MW" },
  { "name": "Malaysia", "isdcode": "+60", "code": "MY" },
  { "name": "Maldives", "isdcode": "+960", "code": "MV" },
  { "name": "Mali", "isdcode": "+223", "code": "ML" },
  { "name": "Malta", "isdcode": "+356", "code": "MT" },
  { "name": "Marshall Islands", "isdcode": "+692", "code": "MH" },
  { "name": "Martinique", "isdcode": "+596", "code": "MQ" },
  { "name": "Mauritania", "isdcode": "+222", "code": "MR" },
  { "name": "Mauritius", "isdcode": "+230", "code": "MU" },
  { "name": "Mayotte", "isdcode": "+262", "code": "YT" },
  { "name": "Mexico", "isdcode": "+52", "code": "MX" },
  {
    "name": "Micronesia, Federated States of Micronesia",
    "isdcode": "+691",
    "code": "FM"
  },
  { "name": "Moldova", "isdcode": "+373", "code": "MD" },
  { "name": "Monaco", "isdcode": "+377", "code": "MC" },
  { "name": "Mongolia", "isdcode": "+976", "code": "MN" },
  { "name": "Montenegro", "isdcode": "+382", "code": "ME" },
  { "name": "Montserrat", "isdcode": "+1664", "code": "MS" },
  { "name": "Morocco", "isdcode": "+212", "code": "MA" },
  { "name": "Mozambique", "isdcode": "+258", "code": "MZ" },
  { "name": "Myanmar", "isdcode": "+95", "code": "MM" },
  { "name": "Namibia", "isdcode": "+264", "code": "NA" },
  { "name": "Nauru", "isdcode": "+674", "code": "NR" },
  { "name": "Nepal", "isdcode": "+977", "code": "NP" },
  { "name": "Netherlands", "isdcode": "+31", "code": "NL" },
  { "name": "Netherlands Antilles", "isdcode": "+599", "code": "AN" },
  { "name": "New Caledonia", "isdcode": "+687", "code": "NC" },
  { "name": "New Zealand", "isdcode": "+64", "code": "NZ" },
  { "name": "Nicaragua", "isdcode": "+505", "code": "NI" },
  { "name": "Niger", "isdcode": "+227", "code": "NE" },
  { "name": "Nigeria", "isdcode": "+234", "code": "NG" },
  { "name": "Niue", "isdcode": "+683", "code": "NU" },
  { "name": "Norfolk Island", "isdcode": "+672", "code": "NF" },
  { "name": "Northern Mariana Islands", "isdcode": "+1670", "code": "MP" },
  { "name": "Norway", "isdcode": "+47", "code": "NO" },
  { "name": "Oman", "isdcode": "+968", "code": "OM" },
  { "name": "Pakistan", "isdcode": "+92", "code": "PK" },
  { "name": "Palau", "isdcode": "+680", "code": "PW" },
  {
    "name": "Palestinian Territory, Occupied",
    "isdcode": "+970",
    "code": "PS"
  },
  { "name": "Panama", "isdcode": "+507", "code": "PA" },
  { "name": "Papua New Guinea", "isdcode": "+675", "code": "PG" },
  { "name": "Paraguay", "isdcode": "+595", "code": "PY" },
  { "name": "Peru", "isdcode": "+51", "code": "PE" },
  { "name": "Philippines", "isdcode": "+63", "code": "PH" },
  { "name": "Pitcairn", "isdcode": "+872", "code": "PN" },
  { "name": "Poland", "isdcode": "+48", "code": "PL" },
  { "name": "Portugal", "isdcode": "+351", "code": "PT" },
  { "name": "Puerto Rico", "isdcode": "+1939", "code": "PR" },
  { "name": "Qatar", "isdcode": "+974", "code": "QA" },
  { "name": "Romania", "isdcode": "+40", "code": "RO" },
  { "name": "Russia", "isdcode": "+7", "code": "RU" },
  { "name": "Rwanda", "isdcode": "+250", "code": "RW" },
  { "name": "Reunion", "isdcode": "+262", "code": "RE" },
  { "name": "Saint Barthelemy", "isdcode": "+590", "code": "BL" },
  {
    "name": "Saint Helena, Ascension and Tristan Da Cunha",
    "isdcode": "+290",
    "code": "SH"
  },
  { "name": "Saint Kitts and Nevis", "isdcode": "+1869", "code": "KN" },
  { "name": "Saint Lucia", "isdcode": "+1758", "code": "LC" },
  { "name": "Saint Martin", "isdcode": "+590", "code": "MF" },
  { "name": "Saint Pierre and Miquelon", "isdcode": "+508", "code": "PM" },
  {
    "name": "Saint Vincent and the Grenadines",
    "isdcode": "+1784",
    "code": "VC"
  },
  { "name": "Samoa", "isdcode": "+685", "code": "WS" },
  { "name": "San Marino", "isdcode": "+378", "code": "SM" },
  { "name": "Sao Tome and Principe", "isdcode": "+239", "code": "ST" },
  { "name": "Saudi Arabia", "isdcode": "+966", "code": "SA" },
  { "name": "Senegal", "isdcode": "+221", "code": "SN" },
  { "name": "Serbia", "isdcode": "+381", "code": "RS" },
  { "name": "Seychelles", "isdcode": "+248", "code": "SC" },
  { "name": "Sierra Leone", "isdcode": "+232", "code": "SL" },
  { "name": "Singapore", "isdcode": "+65", "code": "SG" },
  { "name": "Slovakia", "isdcode": "+421", "code": "SK" },
  { "name": "Slovenia", "isdcode": "+386", "code": "SI" },
  { "name": "Solomon Islands", "isdcode": "+677", "code": "SB" },
  { "name": "Somalia", "isdcode": "+252", "code": "SO" },
  { "name": "South Africa", "isdcode": "+27", "code": "ZA" },
  { "name": "South Sudan", "isdcode": "+211", "code": "SS" },
  {
    "name": "South Georgia and the South Sandwich Islands",
    "isdcode": "+500",
    "code": "GS"
  },
  { "name": "Spain", "isdcode": "+34", "code": "ES" },
  { "name": "Sri Lanka", "isdcode": "+94", "code": "LK" },
  { "name": "Sudan", "isdcode": "+249", "code": "SD" },
  { "name": "Suriname", "isdcode": "+597", "code": "SR" },
  { "name": "Svalbard and Jan Mayen", "isdcode": "+47", "code": "SJ" },
  { "name": "Swaziland", "isdcode": "+268", "code": "SZ" },
  { "name": "Sweden", "isdcode": "+46", "code": "SE" },
  { "name": "Switzerland", "isdcode": "+41", "code": "CH" },
  { "name": "Syrian Arab Republic", "isdcode": "+963", "code": "SY" },
  { "name": "Taiwan", "isdcode": "+886", "code": "TW" },
  { "name": "Tajikistan", "isdcode": "+992", "code": "TJ" },
  {
    "name": "Tanzania, United Republic of Tanzania",
    "isdcode": "+255",
    "code": "TZ"
  },
  { "name": "Thailand", "isdcode": "+66", "code": "TH" },
  { "name": "Timor-Leste", "isdcode": "+670", "code": "TL" },
  { "name": "Togo", "isdcode": "+228", "code": "TG" },
  { "name": "Tokelau", "isdcode": "+690", "code": "TK" },
  { "name": "Tonga", "isdcode": "+676", "code": "TO" },
  { "name": "Trinidad and Tobago", "isdcode": "+1868", "code": "TT" },
  { "name": "Tunisia", "isdcode": "+216", "code": "TN" },
  { "name": "Turkey", "isdcode": "+90", "code": "TR" },
  { "name": "Turkmenistan", "isdcode": "+993", "code": "TM" },
  { "name": "Turks and Caicos Islands", "isdcode": "+1649", "code": "TC" },
  { "name": "Tuvalu", "isdcode": "+688", "code": "TV" },
  { "name": "Uganda", "isdcode": "+256", "code": "UG" },
  { "name": "Ukraine", "isdcode": "+380", "code": "UA" },
  { "name": "United Arab Emirates", "isdcode": "+971", "code": "AE" },
  { "name": "United Kingdom", "isdcode": "+44", "code": "GB" },
  { "name": "United States", "isdcode": "+1", "code": "US" },
  { "name": "Uruguay", "isdcode": "+598", "code": "UY" },
  { "name": "Uzbekistan", "isdcode": "+998", "code": "UZ" },
  { "name": "Vanuatu", "isdcode": "+678", "code": "VU" },
  {
    "name": "Venezuela, Bolivarian Republic of Venezuela",
    "isdcode": "+58",
    "code": "VE"
  },
  { "name": "Vietnam", "isdcode": "+84", "code": "VN" },
  { "name": "Virgin Islands, British", "isdcode": "+1284", "code": "VG" },
  { "name": "Virgin Islands, U.S.", "isdcode": "+1340", "code": "VI" },
  { "name": "Wallis and Futuna", "isdcode": "+681", "code": "WF" },
  { "name": "Yemen", "isdcode": "+967", "code": "YE" },
  { "name": "Zambia", "isdcode": "+260", "code": "ZM" },
  { "name": "Zimbabwe", "isdcode": "+263", "code": "ZW" }
]
